# Generated by Django 2.2.2 on 2019-07-16 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogoDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('detail_option', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'logo_des',
            },
        ),
        migrations.CreateModel(
            name='PatternDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('detail_option', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'pattern_des',
            },
        ),
        migrations.CreateModel(
            name='SocksCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sock_category',
            },
        ),
        migrations.CreateModel(
            name='SocksType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sock_type',
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='ffffff', max_length=10)),
                ('other_req', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='product.SocksCategory')),
                ('logo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.LogoDescription')),
                ('main_type', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='product.SocksType')),
                ('pattern', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.PatternDescription')),
            ],
            options={
                'db_table': 'product_des',
            },
        ),
    ]
