# Generated by Django 2.2.2 on 2019-07-25 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'logo_type',
            },
        ),
        migrations.CreateModel(
            name='PatternType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pattern_type',
            },
        ),
        migrations.CreateModel(
            name='SocksCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sock_category',
            },
        ),
        migrations.CreateModel(
            name='SocksType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sock_type',
            },
        ),
        migrations.CreateModel(
            name='PatternDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=300, null=True)),
                ('pattern_size', models.IntegerField(default=200)),
                ('detail_option', models.TextField(blank=True, max_length=1500, null=True)),
                ('pattern_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.PatternType')),
            ],
            options={
                'db_table': 'pattern_des',
            },
        ),
        migrations.CreateModel(
            name='LogoDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=300, null=True)),
                ('detail_option', models.TextField(blank=True, max_length=1500, null=True)),
                ('logo_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.LogoType')),
            ],
            options={
                'db_table': 'logo_des',
            },
        ),
        migrations.CreateModel(
            name='DesignDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(default='#ffffff', max_length=10)),
                ('photo_url', models.CharField(blank=True, max_length=5000, null=True)),
                ('other_req', models.CharField(blank=True, max_length=500, null=True)),
                ('wished_num', models.IntegerField(default=0)),
                ('sales_volume', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='product.SocksCategory')),
                ('logo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.LogoDescription')),
                ('main_type', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='product.SocksType')),
                ('pattern', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.PatternDescription')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User')),
            ],
            options={
                'db_table': 'design_des',
            },
        ),
    ]
