# Generated by Django 2.2.2 on 2019-07-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logodescription',
            name='detail_option',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
