# Generated by Django 2.2.2 on 2019-07-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patterndescription',
            name='pattern_size',
            field=models.IntegerField(blank=True, default=200, null=True),
        ),
    ]
