# Generated by Django 2.2.2 on 2019-07-16 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190716_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='logodescription',
            name='logo_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.LogoType'),
        ),
        migrations.AddField(
            model_name='patterndescription',
            name='pattern_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.PatternType'),
        ),
    ]
