# Generated by Django 2.2.2 on 2019-07-25 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190725_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='designdescription',
            name='hash_value',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
