# Generated by Django 2.2.2 on 2019-07-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190716_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescription',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
