# Generated by Django 2.2.2 on 2019-07-16 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productdescription_label'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductDescription',
            new_name='DesignDescription',
        ),
    ]
