# Generated by Django 2.2.2 on 2019-07-16 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190716_1248'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='designdescription',
            table='design_des',
        ),
    ]
