# Generated by Django 2.2.3 on 2019-07-24 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_address_addresstype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addresstype',
            table='address_type_list',
        ),
    ]
