# Generated by Django 2.2.3 on 2019-07-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190724_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_num',
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='recepient',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
