# Generated by Django 2.2.3 on 2019-07-22 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190718_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default=0, max_length=20)),
            ],
            options={
                'db_table': 'social_platform',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='social_login_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='social',
            field=models.ForeignKey(blank=True, default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='user.SocialPlatform'),
        ),
    ]
