# Generated by Django 2.2.3 on 2019-07-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190724_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresstype',
            name='address_type',
            field=models.CharField(max_length=20),
        ),
    ]
