# Generated by Django 2.2.3 on 2019-07-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190724_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
