# Generated by Django 2.2.3 on 2019-07-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190722_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialplatform',
            name='platform',
            field=models.CharField(max_length=20),
        ),
    ]
