# Generated by Django 2.2.3 on 2019-07-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190723_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialplatform',
            name='platform',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
