# Generated by Django 2.2.3 on 2019-07-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190723_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialplatform',
            name='platform',
            field=models.CharField(default=3, max_length=20),
        ),
    ]
