# Generated by Django 2.2.3 on 2019-07-24 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20190724_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'address_type_list',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='reward_points',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.AddressType')),
                ('address', models.CharField(max_length=100)),
                ('recepient', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
